### ISSUE TITLE
Internal server error returned intermittently 

### ISSUE THREAD

**Issue by petervolvowinz** [remotivelabs/remotivelabs-community#5]
Streaming unexpectedly finished when using RL cloud playback from a Rust client.  Behavior also reported from Android client.

**Data source:** 
Jeremy sunnnyvale drive
configuration_xc90

**Broker:**
vss-aaos

Stacktrace below from following code snippet:

```
// run the signal broker in an infinite loop
async fn run_broker() -> Result<(), Box<dyn Error>> {
    let stream = BrokerConfiguration::connect().await;
    match stream {
        Err(ref e) => panic!("initial connection to broker failed {:?}", e),
        Ok(ref _t) => println!("connection to broker ok")
    }
    let mut signal_stream = stream.unwrap();

    let mut d_board = Dashboard::new("".to_string(), "".to_string(), 0.0);
    loop {
        if let signals = signal_stream.message().await? {
            match signals {
                Some(sigs) => {
                    d_board.traverse_print(sigs);
                }
                None => {
                    println!("none received")
                }
            }
        } else {
            break;
        }
    }

    Ok(())
}
```

MODEL: V526 XC90
SPEED: [                                            xxxxx@xxxxx                                             ]
thread ‘main’ panicked at ‘TODO: panic message: Status { code: Unknown, message: “Internal Server Error”, source: None }’, src/main.rs:10:24
stack backtrace:
   0:        0x104810644 - std::backtrace_rs::backtrace::libunwind::trace::h72c73b9e5db0005d
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:        0x104810644 - std::backtrace_rs::backtrace::trace_unsynchronized::h0241cec881bc8f92
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x104810644 - std::sys_common::backtrace::_print_fmt::h7a7ee67e414bd3d7
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:66:5
   3:        0x104810644 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2990a6f24ccff6db
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:45:22
   4:        0x104829678 - core::fmt::write::h91497fd291c8b104
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/fmt/mod.rs:1202:17
   5:        0x10480b9e8 - std::io::Write::write_fmt::h23fa41342cffacf4
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/io/mod.rs:1679:15
   6:        0x104811c20 - std::sys_common::backtrace::_print::h39f712a9b74dd89c
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:48:5
   7:        0x104811c20 - std::sys_common::backtrace::print::h0be19d9a7285bd90
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:35:9
   8:        0x104811c20 - std::panicking::default_hook::{{closure}}::hb41cdb784f4c17ac
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:295:22
   9:        0x104811944 - std::panicking::default_hook::hdfe992d5fb29a991
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:314:9
  10:        0x1048121b8 - std::panicking::rust_panic_with_hook::h2eb0e4b718773521
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:698:17
  11:        0x1048120f0 - std::panicking::begin_panic_handler::{{closure}}::h06a693206403b4d5
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:588:13
  12:        0x104810aac - std::sys_common::backtrace::__rust_end_short_backtrace::h8998defd518dbcad
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:138:18
  13:        0x104811e44 - rust_begin_unwind
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
  14:        0x10483a4c4 - core::panicking::panic_fmt::ha46aa9af97eb193d
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
  15:        0x10483a5b0 - core::result::unwrap_failed::h730969f28291ae99
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/result.rs:1785:5
  16:        0x10427af30 - core::result::Result<T,E>::expect::he5497cab80386be8
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/result.rs:1064:23
  17:        0x10428f1e8 - rl_rust::main::{{closure}}::h9792518c280733e9
                               at /Users/PWINZELL/CLionProjects/rl-rust/src/main.rs:10:5
  18:        0x1042949f8 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h1258e567fa8b4199
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/future/mod.rs:91:19
  19:        0x104287a84 - tokio::runtime::park::CachedParkThread::block_on::{{closure}}::h4e3273f30ea8b01b
                               at /Users/PWINZELL/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/park.rs:283:63
  20:        0x104287508 - tokio::runtime::coop::with_budget::hfe25cbddad4b8d4e
                               at /Users/PWINZELL/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/coop.rs:107:5
  21:        0x104287508 - tokio::runtime::coop::budget::h9e52980fa0d4f063
                               at /Users/PWINZELL/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/coop.rs:73:5
  22:        0x104287508 - tokio::runtime::park::CachedParkThread::block_on::hbbdf1ca8be0dc4a0
                               at /Users/PWINZELL/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/park.rs:283:31
  23:        0x104271e0c - tokio::runtime::context::BlockingRegionGuard::block_on::h20dd3c6c40cb2c05
                               at /Users/PWINZELL/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/context.rs:315:13
  24:        0x104291ddc - tokio::runtime::scheduler::multi_thread::MultiThread::block_on::h270c1c8961cf9b2b
                               at /Users/PWINZELL/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/scheduler/multi_thread/mod.rs:66:9
  25:        0x104279160 - tokio::runtime::runtime::Runtime::block_on::hb9b6453132a86efe
                               at /Users/PWINZELL/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/runtime.rs:304:45
  26:        0x104276a64 - rl_rust::main::he2f31259abad383d
                               at /Users/PWINZELL/CLionProjects/rl-rust/src/main.rs:11:5
  27:        0x104266b44 - core::ops::function::FnOnce::call_once::h4665630095f08aa3
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/ops/function.rs:248:5
  28:        0x104279014 - std::sys_common::backtrace::__rust_begin_short_backtrace::he5a87ac278527d73
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:122:18
  29:        0x10427560c - std::rt::lang_start::{{closure}}::h8ce6942e089e73a2
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/rt.rs:166:18
  30:        0x104807fd0 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h0c60ab225fafdaa1
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/ops/function.rs:283:13
  31:        0x104807fd0 - std::panicking::try::do_call::he83c34dec7ecf156
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:492:40
  32:        0x104807fd0 - std::panicking::try::hf8a127683312d6e6
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:456:19
  33:        0x104807fd0 - std::panic::catch_unwind::h6bfb2185c735f4ae
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panic.rs:137:14
  34:        0x104807fd0 - std::rt::lang_start_internal::{{closure}}::he1235e45f833117a
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/rt.rs:148:48
  35:        0x104807fd0 - std::panicking::try::do_call::h600fcfa83f96c092
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:492:40
  36:        0x104807fd0 - std::panicking::try::h3ab439188ed13993
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:456:19
  37:        0x104807fd0 - std::panic::catch_unwind::hb86c613836afcf80
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panic.rs:137:14
  38:        0x104807fd0 - std::rt::lang_start_internal::h94fa211da9d06d56
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/rt.rs:148:20
  39:        0x1042755d4 - std::rt::lang_start::h937e0d92d3411819
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/rt.rs:165:17
  40:        0x104276b10 - _main

**Comment by jrask** [comment]
@petervolvowinz - Can you also give me the project name you are working in + a timestamp when this occurred and I will see if I can help out.

**Comment by petervolvowinz** [comment]
added crash with ts.
```Received at: 2023-06-28 15:26:17.995859 UTC
VIN: 
MODEL: V526 XC90
SPEED: [                                      xxxxxxxxxxx@xxxxxxxxxxx                                       ]
thread 'main' panicked at 'TODO: panic message: Status { code: Unknown, message: "Internal Server Error", source: None }', src/main.rs:12:24
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
(base) PWINZELL@YM739X2WNN rl-rust % 
```

**Comment by petervolvowinz** [comment]
Added with ts:
```
Received at: 2023-06-28 15:26:17.995859 UTC
VIN: 
MODEL: V526 XC90
SPEED: [                                      xxxxxxxxxxx@xxxxxxxxxxx                                       ]
thread 'main' panicked at 'TODO: panic message: Status { code: Unknown, message: "Internal Server Error", source: None }', src/main.rs:12:24
```

**Comment by petervolvowinz** [comment]
Note the broker continues running and you are able to restart application. It could of course be something in the client gRPC code as well.

**Comment by jrask** [comment]
@petervolvowinz - You are running Lua code?

**Comment by petervolvowinz** [comment]
Not that i am aware of. I am not sure how the mapping to vss is done broker side. I am just running a rust gRPC client

Hämta Outlook för iOS<https://aka.ms/o0ukef>
________________________________
Från: Johan Rask ***@***.***>
Skickat: Thursday, June 29, 2023 7:22:03 AM
Till: remotivelabs/remotivelabs-community ***@***.***>
Kopia: Winzell, Peter ***@***.***>; Mention ***@***.***>
Ämne: Re: [remotivelabs/remotivelabs-community] Internal server error returned intermittently (Issue #5)


@petervolvowinz<https://github.com/petervolvowinz> - You are running Lua code?
